spring:
  application:
    name: @project.artifactId@
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
